app_settings:
    TIMEOUT_IN_SECONDS: 60
    job_orchestrator_function_app_name: fa-${ENVIRONMENT}-uks-nomad-02-job-orchestrator
    azure_client_id: ${AZURE_CLIENT_ID}
    service_bus:
        processed_queue_name: ${SB_PROCESSED_QUEUE_NAME}
        pre_processed_queue_name: ${SB_PRE_PROCESSED_QUEUE_NAME}
        namespace_fqdn: ${SB_NAMESPACE_FQDN}

# Logger
logging:
    config: classpath:log4j2-cloud.xml