app_settings:
    TIMEOUT_IN_SECONDS: -1
    job_orchestrator_function_app_name: fa-${ENVIRONMENT}-uks-nomad-02-job-orchestrator
    service_bus:
        processed_queue_name: nomad_processed
        pre_processed_queue_name: nomad_pre_processed
        namespace_fqdn: sbns-${ENVIRONMENT}-uks-nomad-02.servicebus.windows.net

# Logger
logging:
    config: classpath:log4j2-hetzner.xml