spring:
    application:
        name: job_orchestrator
    profiles:
        active: ${SPRING_PROFILE:local}
    jpa:
        hibernate:  # Dont create anything in the DB based on our Entities.
            ddl-auto: none
