
name: deploy-admin-api-azure-functions
run-name: Deploy Admin-Api Azure Functions

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev

env:
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '17'
  MODULE_DIR: ./job_orchestrator

permissions:
  id-token: write

jobs:
  build-and-deploy:
    env:
      FUNCTION_APP_NAME: fa-${{ github.event.inputs.environment }}-uks-nomad-02-job-orchestrator
      FUNCTION_APP_RG_NAME: rg-${{ github.event.inputs.environment }}-uks-nomad-02
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Mvn clean package
        shell: bash          
        run: |
          mvn clean package -pl job_orchestrator -am -DfunctionAppName=$FUNCTION_APP_NAME -DfunctionResourceGroup=$FUNCTION_APP_RG_NAME

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: '${{ env.MODULE_DIR }}/target/azure-functions/${{ env.FUNCTION_APP_NAME }}' # if there are multiple function apps in same project, then this path will be like './${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }'
          sku: flexconsumption
          respect-pom-xml: true
          