name: Maven deploy common_data library
run-name: Maven deploy common_data library

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

# permissions:
#   checks: write

jobs:
  maven-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


    # - name: Publish parent to GitHub Packages Apache Maven
    #   run: |
    #     mvn deploy -pl data-services -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}

    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn deploy -pl data-library -am -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}